### ISSUE TITLE
It lacks a space character between the word 'Receiving' and the amount in HUSH.

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonAndroid#21]
It lacks a space character between the word 'Receiving' and the amount in HUSH.

It may be necessary to shift the receiver block to the left to prevent the line is cut.

![Screenshot_20191115-013938_SilentDragon](https://user-images.githubusercontent.com/39105646/68907825-7549cf80-0749-11ea-8718-8f0586c3d9e9.jpg)

**Comment by gilardh** [comment]
After correct :
![Screenshot_20191116-000635_SilentDragon](https://user-images.githubusercontent.com/39105646/68985708-c70d5b00-0818-11ea-9c35-6fb7301238f2.jpg)


For now, I don't have shift the receiver block to the left to prevent the line is cut.

**Comment by jahway603** [comment]
@gilardh Did Pull Request #28 fix this?

**Comment by jahway603** [comment]
Closing as #28 appears to have fixed it.
