### ISSUE TITLE
404 Page not found when clic on eyes of 'Confirm & send 'page

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonAndroid#52]
On send confirmation page, there is an eye on the top right.
If we click on it, it makes appear a page 404.

![Screenshot_20191123-234058_SilentDragon](https://user-images.githubusercontent.com/39105646/69486555-43252580-0e4d-11ea-8585-5d3e256e9e9c.jpg)
![Screenshot_20191123-234103_SilentDragon](https://user-images.githubusercontent.com/39105646/69486557-44eee900-0e4d-11ea-9cb4-dba633965eeb.jpg)

**Comment by leto** [comment]
@gilardh it's rendering a link before the transaction is sent, so the explorer doesn't have it yet. Not sure the best thing to do

**Comment by leto** [comment]
@gilardh i think that we should not render the eye link until after the transaction is sent. There is still a tiny possibility the user clicks on it and the explorer doesn't have it yet, but that is small

**Comment by leto** [comment]
fixed
