### ISSUE TITLE
Improve installation screen

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonAndroid#6]
Lots of empty space there, let's make it pretty

**Comment by mmeister1203** [comment]
@leto The installation screen is a system view and we don't have control over the customization of it... :(

**Comment by leto** [comment]
@mmeister1203 so we are allowed to put text, and nothing else? What about links?

**Comment by leto** [comment]
Newer android systems have a more pleasant install screen, this is not relevant anymore
