### ISSUE TITLE
Improve the "Error Sending Transaction" popup

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonAndroid#7]
Currently says "Can't spend more than HUSH 5 in a single Tx" which is worded badly and isn't even correct.

Should be "You tried to spend X HUSH but there is only Y HUSH in your address currently. You might need to sweep funds into one address or wait for some funds to confirm"

**Comment by leto** [comment]
This error can be confusing for users. We need to explain to them that SDA can only send funds from a single address, so they might have enough funds in their *wallet*, there needs to be enough in a single address, to send out.

**Comment by jahway603** [comment]
Fixed in pull #111
