### ISSUE TITLE
Declare compatibility back to 4.4 Kitkat on Google Play

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonAndroid#79]
Right now older Androids can download our app and it won't work because they are not compatible. I think there is a setting in the Play store to declare what we support, hopefully?

**Comment by jahway603** [comment]
This app's minSdkVersion is already set to 17 [Android 4.2.x], so I believe this application is supported for Android 4.4 already. I was able to compile and run it on Android 5.1.x device.

Google PlayStore requires targetSdkVersion to be set to at least 26 for submission ([XDA Source Article](https://www.xda-developers.com/developers-new-app-play-store-api-level-26/)), which might be the issue you're describing.

According to this ([new Android OS distribution chart](https://androiddistribution.io)), only 4% of the Android ecosystem runs 4.4 KitKat, so does it make sense to support this version still?

**Comment by leto** [comment]
@jahway603 i agree, it's annoying to do and probably not very important. People can always download from Github if necessary. Closing
